### ISSUE TITLE
A couple of issues

### ISSUE THREAD

**Issue by wingnut02** [echocoderxbmc/plugin.video.xxx-o-dus#10]
First of all, let me commend you and say thank you for such an excellent plugin! It is the best available!

When you click on Issues to view the Issues, you can not view the Closed Issues. Clicking on it does nothing, unlike when you click on Open Issues, which opens a new window and displays them.

Secondly, under Live Cams, then under Chaturbate, clicking on any of the Cams options displays a list of viewable cams which is in the "Widelist" viewtype. Changing the viewtype to "Shift", displays them in the "Shift" viewtype, but only until you click  on "Next Page" or go back to the list of Cam options. Then it goes back to the "Widelist". It never remembers the viewtype that you have chosen.

I hope I've given you enough info...

Thanks a bunch!

**Comment by echocoderxbmc** [comment]
I will check out the closed issues tomorrow.

The issue with the view change is hard for me to do much about, you could change the view modes in the settings to represent the modes you want? Please let me know if this works for you or if thats a problem.

Thanks in advance.

**Comment by wingnut02** [comment]
I just tried that at your suggestion. Since I didn't know which view mode was used fir the list of cam performers I changed all of them from mode 0 to 1, saved the settings, and went back in ti look at the list. It appears to have had no effect. I then tried changing them all to 2, saving settings, exiting all the way out of kodi, going back in, and still nothing. 




Do you have the source code for the chaturbate addon? I'm not a python coder, but I've been coding in Delphi and VB for a living for the past 22 years. Maybe I could help?




From: Echo Coder


Sent: Friday, August 4, 7:32 PM


Subject: Re: [echocoderxbmc/plugin.video.xxx-o-dus] A couple of issues (#10)


To: echocoderxbmc/plugin.video.xxx-o-dus


Cc: wingnut02, Author






I will check out the closed issues tomorrow.


The issue with the view change is hard for me to do much about, you could change the view modes in the settings to represent the modes you want? Please let me know if this works for you or if thats a problem.


Thanks in advance.

**Comment by echocoderxbmc** [comment]
Hey,

The source code for the chaturbate scraper is here: https://github.com/echocoderxbmc/script.xxxodus.scrapers/blob/master/lib/scrapers/chaturbate.py

With the veiw modes you have to tell the addon which mode you want to use for the skin you are using (All skins have different modes)

If you navigate to the skin folder in the addons folder you will be able to see inside one of the folders all the views.

For example list_55.xml 

In that instance list mode would be mode 55

shift_500.xml would mean shift mode is 500

So then go the settings and set the mode for the view you want. Its hard for me to do it any other way because of the way each skin has different views.

The other option would be to set a chatutbate specific view type but again that would need to be manually set.

I will take a look into it some more today tho.

**Comment by echocoderxbmc** [comment]
If you bring up the context menu on any item in xxxodus you can save the view mode for the addon to remember. So go to chaturbate, change the view, bring up the context menu and set the view. Hope this helps. Also closed issues should be fixed now too.

**Comment by wingnut02** [comment]
I looked through almost every folder under the kodi and never did find a skin folder under addons.




From: Echo Coder


Sent: Saturday, August 5, 4:08 AM


Subject: Re: [echocoderxbmc/plugin.video.xxx-o-dus] A couple of issues (#10)


To: echocoderxbmc/plugin.video.xxx-o-dus


Cc: wingnut02, Author






Hey,


The source code for the chaturbate scraper is here: https://github.com/echocoderxbmc/script.xxxodus.scrapers/blob/master/lib/scrapers/chaturbate.py


With the veiw modes you have to tell the addon which mode you want to use for the skin you are using (All skins have different modes)


If you navigate to the skin folder in the addons folder you will be able to see inside one of the folders all the views.


For example list_55.xml


In that instance list mode would be mode 55


shift_500.xml would mean shift mode is 500


So then go the settings and set the mode for the view you want. Its hard for me to do it any other way because of the way each skin has different views.


The other option would be to set a chatutbate specific view type but again that would need to be manually set.


I will take a look into it some more today tho.
