### ISSUE TITLE
Sites not working

### ISSUE THREAD

**Issue by imurreflection** [echocoderxbmc/plugin.video.xxx-o-dus#12]
Hello Mate..Good Day ! Just to let you know some sites like Fuqer, Gotporn,Hclips and Voyeurhit are not working. They are working fine on mobile and pc browser.

**Comment by echocoderxbmc** [comment]
Hello,

I fixed the resolver for Hclips and Voyeurhit last night so they will be updated to the resolver either tonight or tomorrow.

I have looked at Fuqer and Gotporn and both are working fine for me.

If you could give me some more information on whats not playing/loading and if your able to attach a log that would be great.

Thank you.
