### ISSUE TITLE
Chaturbate web cams down

### ISSUE THREAD

**Issue by Haddonfieldelm** [echocoderxbmc/plugin.video.xxx-o-dus#16]
Only HD cams are working in chaturbate. everything else gives an error message "xxx-o-dus error. check the log for more info"
![20170808_222906](https://user-images.githubusercontent.com/30851455/29102751-417e782e-7c89-11e7-902b-7f752b2b172c.jpg)

**Comment by echocoderxbmc** [comment]
Thanks, please check the Closed Issues tab. This was reported yesterday, I have fixed it and I till release the update some time today. Thanks for reporting it :-)
