### ISSUE TITLE
Site Addition Request

### ISSUE THREAD

**Issue by imurreflection** [echocoderxbmc/plugin.video.xxx-o-dus#17]
Hi my friend, please see if you can add sexhayvc.com. Site has multiple categories in Asian porn with direct playable links. Thank you for your great work and have a nice day.

**Comment by echocoderxbmc** [comment]
Hello mate. 

I have had a little look and it does not seem an easy site to get the links from. On the examples I have looked at I see no direct links in the source but instead links compiled by javascript. Whilst doable at the present time Im short on tome to spend on websites that are harder to do and may change to break my scrape. Hope this helps. If you have any more suggestions please let me know.

**Comment by imurreflection** [comment]
No worries mate. Thank you for the quick response. Once, you have some time, kindly add it. Have a nice day !!!
