### ISSUE TITLE
Cam categories error

### ISSUE THREAD

**Issue by wingnut02** [echocoderxbmc/plugin.video.xxx-o-dus#18]
None of the different Cam catergories in Chaturbate are working except for "Rooms by tag"...

**Comment by echocoderxbmc** [comment]
Please check the closed issues.

**Comment by wingnut02** [comment]
So it's an issue with Chaturbate themselves?




On Wed, Aug 9, 2017 at 10:08 AM -0400, "Echo Coder" <notifications@github.com> wrote:












Please check the closed issues.
