### ISSUE TITLE
download menu malfunction

### ISSUE THREAD

**Issue by narcjoe** [echocoderxbmc/plugin.video.xxx-o-dus#19]
![screenshot 14](https://user-images.githubusercontent.com/29749344/29179636-ed0bc784-7da9-11e7-9b0d-79d639d40741.png)

**Comment by echocoderxbmc** [comment]
Ah i see, ok thank you very much I will look into it.

**Comment by narcjoe** [comment]
this appears to be happening on the first video from one site, after the last video from another site.  example the last video shown from madthumbs,and say the next site is pornhub, it would be the 1st from pornhub

**Comment by echocoderxbmc** [comment]
Issue has been fixed with a PR from the developer of Whitecream here: 

https://github.com/echocoderxbmc/plugin.video.xxx-o-dus/pull/22
