### ISSUE TITLE
urlresolver

### ISSUE THREAD

**Issue by meddle99** [echocoderxbmc/plugin.video.xxx-o-dus#21]
Ok -- most people apparently do not have this issue so I am doing something wrong.  Every time I try to load this addon, I get a message that the urlresolver dependency could not be satisfied.  I have loaded the urlreslover from this repo and it reported success.

**Comment by echocoderxbmc** [comment]
Do you have the colossus repo installed? Make sure you install the addon from the colossus repo and nowhere else.

**Comment by meddle99** [comment]
Thank you.  I knew nothing about the colossus repo.  I was trying to install from here.
