### ISSUE TITLE
Youporn

### ISSUE THREAD

**Issue by lexusman2000** [echocoderxbmc/plugin.video.xxx-o-dus#23]
Youporn is not working  when you open  it you can see the video but it won't  play nothing at all

**Comment by echocoderxbmc** [comment]
Hello,

I have just tested the YouPorn section and all the links I tried failed.

Could you please go to the Debug Versions option on the main menu and feedback the versions you have please.

**Comment by echocoderxbmc** [comment]
No more comments so closing the issue.
