### ISSUE TITLE
Vintage section

### ISSUE THREAD

**Issue by razes13** [echocoderxbmc/plugin.video.xxx-o-dus#26]
Unable to use Next page in every category of the Vintage section (getting Scrapping Error). Only one page is available. Some days unable even to view some categories at all.
https://paste.drhack.net/?2a0cdb0b276cbdfb#d4WUJXMX/Yzi4x7aM06PIIPhbTFcZvz4wXXEPKoewxk=

Scrapping errors in log file are on 12:53:11 and 12:58:41

**Comment by echocoderxbmc** [comment]
It seems to be an issue with the site, if you visit the site and go to cats and click the cats they do not load, I have a work around while the site is messing up so I will try and get it out tonight.

**Comment by echocoderxbmc** [comment]
I have just pushed XXXODUS Scrapers 1.00.022, this should fix your issue. Please test and let me know.

Thanks

**Comment by razes13** [comment]
Thank you for your update. Now Vintage section is OK more or less. I
checked several categories. Everything is looking good except Group and DP
which are stuck on a second page for unknown reasons (in both KOdi 16.1 and
17.3). But that is not critical.
