### ISSUE TITLE
Previously Watched Videos no Longer Appearing

### ISSUE THREAD

**Issue by Coleorton** [echocoderxbmc/plugin.video.xxx-o-dus#28]
I have an issue with my addon, I go into my history to rewatch videos, and when I select them, they don't play, the loading/working symbol comes up for a second then nothing happens, nearly all of my videos in my history won't play back and I can't find them either, yet when I go onto the tubes respective websites the videos in my history are still there up and running, any idea on how to fix this?

Thanks.

**Comment by echocoderxbmc** [comment]
Just for testing purposes could you please direct me to a video we can both test and if possible please upload a log.

**Comment by Coleorton** [comment]
I use Kodi on an Android box and not on PC or anything like that just so you know.

Do you know how I can view the log? I can just type it out once I find it.

**Comment by echocoderxbmc** [comment]
Just do a quick google on "kodi upload log android" there should be a few tutorials there for you mate.

**Comment by Coleorton** [comment]
And this problem has only started yesterday, other than yesterday and today it worked fine. The history includes different videos from different tubes.

However, if I was to watch a video now and watch it again by going into my history, it'd work, but not the videos I've watched in the past. In fact, the videos I now watched yesterday don't work today now aswell.

The relevant log for a single video (I think):

00:00:38 T:18446744072355316688 ERROR: CDVDPlayer ;;OpenInputStream - error opening [http://content.xvideos.com/videos/mp4/7/3/5/xvideos.com_73580bc29fd27a02b1648cebe2fe5695.mp4?e=15

ERROR: virtual bool XFILE;;CFileCache;;Open(const CURL&) - failed to open source
Error CCurlFile;;Open failed with code 403 for http://content.xvideos.com/videos/mp4/7/3/5/xvideos.com_73580bc29fd27a02b1648cebe2fe5695.mp4?e=150
Error CCurlFile;;FillBuffer - failed;HTTP returned error 403
Error CCurlFile;;Stat - Failed; HTTP reponse code said error(22) for http://content.xvideos.com/videos/mp4/7/3/5/xvideos.com_73580bc29fd27a02b1648cebe2fe5695.mp4?e=150  DEBUG; Thread LanguageInvoker 18446744072362623296 terminating

**Comment by echocoderxbmc** [comment]
I have just pushed 3.00.028

The fix I have made will not work for the existing videos you have but if you could test from this point on and let me know I would appreciate it. 

I will close the issue but if the issue persists please reply and I will reopen this issue.

Thanks

**Comment by Coleorton** [comment]
I watched a video on the 27th, then went to rewatch it on the 28th and it worked! The patch fixed it up.

Any idea on how to get the previous non-working videos to work again? Reset the addon? Uninstall etc?

Thanks.
