### ISSUE TITLE
Possible interesting website

### ISSUE THREAD

**Issue by Oxycon25** [echocoderxbmc/plugin.video.xxx-o-dus#4]
Hi

I see you're working hard to make this addon the best XXX-Kodi addon available. That is why I would like to share this website with you: streamingporn.xyz 

This site has a lot of content and got openload as well as rapidvideo links. If you can integrate it in the addon. Other likewise websites are: hd.xtapes.to - pandamovie.eu/adult/ - xopenload.com - watchporn-online.u

Hopefully this was helpful. Thanks for the addon.

**Comment by echocoderxbmc** [comment]
Thank you, I have added streamingporn and will look at the others over the coming days.
