### ISSUE TITLE
Live channels and movies

### ISSUE THREAD

**Issue by rockinrichy** [echocoderxbmc/plugin.video.xxx-o-dus#5]
Hi. Firstly thanks for keeping XXX-O-DUS alive.
Will you be adding live channels and full length movies which were options in version 2.xx of the addon?
Cheers
Rich

**Comment by echocoderxbmc** [comment]
I will not be adding live channels as this would be a breach of copyright. I will be adding full movies, infact some were added yesterday in the scenses section and I will listen again to any suggestions but I will not add things that will make the addon illegal in parts of the world.

**Comment by rockinrichy** [comment]
Fantastic thank you. If you could possibly add a section for full movies rather than scenes, that would be awesome.
Thanks again.
