### ISSUE TITLE
Site Addition Request. 

### ISSUE THREAD

**Issue by imurreflection** [echocoderxbmc/plugin.video.xxx-o-dus#6]
Hi,  thank you for your wonderful work on this addon and I simply love it.  I just want to make a request if we can add Javtasty.com please.  This site has excellent collection of Asian porn with direct playable links.  Most of the links are in HD.  This will be a great addition to our already great addon since this will b first Japanese porn site Addition from the world's biggest porn industry and once again,  thanks for this great addon

**Comment by echocoderxbmc** [comment]
I have added it, but an awful lot of the videos on the website do not play so I will keep an eye.

**Comment by imurreflection** [comment]
Thanks a lot mate.. Keep don't know if there is an issue with url resolver for Kodi but on normal PC or Mobile browser, every link works just fine.  May I please know where can I find this site in your addon to check this further.  I m currently on 3.00.019. I have forced check for the update but it seems this is the latest we have. 

Also,  please note that you can close ID4 issue as you have already added the site mate.  

_Sent from my Xiaomi MI MAX using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by imurreflection** [comment]
I m sorry Bro,  you are correct.  Most of the links on initial pages are not working but when you do a search example heyzo,  you will find working links.  I apologize for the inconvenience.  Please see if you can add any Japanese porn site whenever you think you can.  

_Sent from my Xiaomi MI MAX using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
