### ISSUE TITLE
Thanks a lot. You are awesome

### ISSUE THREAD

**Issue by imurreflection** [echocoderxbmc/plugin.video.xxx-o-dus#7]
Hey mate,  thanks a ton for adding Javtasty.com.  May I also request to add a changelog in your addon so that we can know what has been added/removed/new features etc please as this addon is growing exponentially. Also,  if you need any help for any testing on PC or Kodi box,  please let me know and thanks again Bro.

**Comment by echocoderxbmc** [comment]
Thank you :-)

Changelog added to main menu
