### ISSUE TITLE
Movies

### ISSUE THREAD

**Issue by ciro84uk23** [echocoderxbmc/plugin.video.xxx-o-dus#9]
Hi thanks for adding the movies but none of the movies are working and there is a lot less than you had on your old repo hope you can fix this many thanks

**Comment by echocoderxbmc** [comment]
If movies are not working for you its because you do not have an up to date smu or your isp is blocking. They all work great here.

**Comment by ciro84uk23** [comment]
hi when i go into movies then steaming porn full movies everyone that you click on is bangbros and its the same clip on everything

**Comment by imurreflection** [comment]
Hi, i was experiencing the same issue but was greatly supported here. All you need to do is to force check for updates and you will find adult url resolver SMU extension. If you do not find it ,you can google it or search on github.com. Install it manually using 'install from Zip File'  Once you update this, all playable links should work. Please ensure you check the website on PC or Mobile browser for the same link.

**Comment by ciro84uk23** [comment]
none of that worked for me sorry but thanks for your help

**Comment by imurreflection** [comment]
Mate, check this link and follow instructions please https://www.google.co.in/amp/www.ares-portal.com/kodi-addons/all-module-addons/adult-resolver-smu-extension/amp/

**Comment by imurreflection** [comment]
And this link on how to install from zip file
http://bestforkodi.com/how-to-install-from-ziprepo-in-kodi-17-krypton/

**Comment by imurreflection** [comment]
[script.module.urlresolver.xxx-1.0.05.zip](https://github.com/echocoderxbmc/plugin.video.xxx-o-dus/files/1201096/script.module.urlresolver.xxx-1.0.05.zip)

**Comment by imurreflection** [comment]
This is SMU. Script Module URL resolver. Just install it using the link i have provided and you should be good to go. Have a nice day !

**Comment by ciro84uk23** [comment]
hi i all ready had it but i have installed the one you provided but still not woking go and do this please go to steaming porn then full movies and try a few of them out i can guarentee everyone that you click on is bangbros and it will be a girl with black and white stripe top

**Comment by imurreflection** [comment]
Sorry about that mate.when you asked what is SMU, I thought you may not know core of Kodi. Now, I checked as you said and you are correct, all links are playing one video file only and now only Echo bro can extend his expertise. And yes, Vintage also gives me scraping error.

_Sent from my Xiaomi MI MAX using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ciro84uk23** [comment]
ok i new it would not only be me that would be having this problem lol fingers crossed he fixes them what isp you with and in in uk iv tried vpn as well rapidvideo still dont work

**Comment by imurreflection** [comment]
Mate, I m from India.

_Sent from my Xiaomi MI MAX using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ciro84uk23** [comment]
echocoderxbmc i dont understand why your still adding movies to steaming porn as the links are playing the same thing like me and the other guy has said we are trying to help not have a dig at you this is the whole point of this issuse report section

**Comment by echocoderxbmc** [comment]
What do you mean? Why am I still adding links? I will check your issue at now and report back.

**Comment by echocoderxbmc** [comment]
Ok so 3.00.021 just pushed. All issues in here should be fixed. Please let me know if you have any issues. If i do not hear anything in 24 hours I will close the issue. Thank you :-)

**Comment by ciro84uk23** [comment]
hi not a problem i will get back to you as soon as the repo is updated and many thanks

**Comment by ciro84uk23** [comment]
hi got it updated to 3.00.021 but when clicking on any movie get xxx-o-dus error then at bottom right just keeps saying working then i have to force close kodi as it wont stop lol

**Comment by echocoderxbmc** [comment]
Please force check the repo for updates to make sure you have all the versions updated.

Once done, if you still have an issue let me know the video so I can test please.

**Comment by ciro84uk23** [comment]
hi iv checked and everything is updated and on both movie sections whe you click on something come up  xxx-o-dus error check the logs for more info then at bottom right just keeps saying working and you need to force close kodi as it not letting me do anything

**Comment by echocoderxbmc** [comment]
Just had a look now before going to bed and found the issue, ive fixed it and pushed an update 022 so please give it a few mins and check and it should work. Sorry about that, you change one thing to make watchxxxfree work and it breaks everything else lol.

**Comment by ciro84uk23** [comment]
ok thank you very much thought it mite be something like that buddy sods law lol

**Comment by ciro84uk23** [comment]
hi seems to be working great now thank you very much for your help and time and for fixing this your a star buddy

**Comment by imurreflection** [comment]
I am not sure what has been fixed but I don't see "Full Movies" tag under streamingporn.xyz anymore. I am on 022.

_Sent from my Xiaomi MI MAX using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
